import type { apiContract } from "./contract.js";
import type { InferSchema } from "./schema.js";

type Schemas = typeof apiContract.schemas;

export type ApiSchemaName = keyof Schemas;
export type ApiDto<Name extends ApiSchemaName> = InferSchema<Schemas[Name], Schemas>;
export type ApiRouteDefinition = (typeof apiContract.routes)[number];

export type ProblemDetailsDto = ApiDto<"ProblemDetails">;
export type LegacyErrorDto = ApiDto<"LegacyError">;
export type PaginationDto = ApiDto<"Pagination">;

export type BookmarkDto = ApiDto<"Bookmark">;
export type BookmarkDetailDto = ApiDto<"BookmarkDetail">;
export type BookmarkCreateRequestDto = ApiDto<"BookmarkCreateRequest">;
export type BookmarkUpdateRequestDto = ApiDto<"BookmarkUpdateRequest">;
export type BookmarkListResponseDto = ApiDto<"BookmarkListResponse">;
export type BookmarkArrayResponseDto = ApiDto<"BookmarkArrayResponse">;
export type BookmarkResponseDto = ApiDto<"BookmarkResponse">;
export type BookmarkDetailResponseDto = ApiDto<"BookmarkDetailResponse">;
export type BookmarkPipelineStatusResponseDto = ApiDto<"BookmarkPipelineStatusResponse">;
export type RelatedBookmarksResponseDto = ApiDto<"RelatedBookmarksResponse">;
export type ReprocessRequestDto = ApiDto<"ReprocessRequest">;
export type ReprocessBatchDto = ApiDto<"ReprocessBatch">;
export type ReprocessBatchResponseDto = ApiDto<"ReprocessBatchResponse">;
export type ReprocessBatchStatusDto = ApiDto<"ReprocessBatchStatus">;
export type ReprocessBatchStatusResponseDto = ApiDto<"ReprocessBatchStatusResponse">;

export type SearchResponseDto = ApiDto<"SearchResponse">;
export type CategoryRecordDto = ApiDto<"CategoryRecord">;
export type CategoryWithCountDto = ApiDto<"CategoryWithCount">;
export type CategoryDto = CategoryRecordDto;
export type CategoryNodeDto = ApiDto<"CategoryNode">;
export type CategoryRequestDto = ApiDto<"CategoryRequest">;
export type CategoryPatchRequestDto = ApiDto<"CategoryPatchRequest">;
export type CategoryTreeResponseDto = ApiDto<"CategoryTreeResponse">;
export type CategoryResponseDto = ApiDto<"CategoryResponse">;
export type TagRecordDto = ApiDto<"TagRecord">;
export type TagWithCountDto = ApiDto<"TagWithCount">;
export type TagDto = TagRecordDto;
export type TagRequestDto = ApiDto<"TagRequest">;
export type TagListResponseDto = ApiDto<"TagListResponse">;
export type TagResponseDto = ApiDto<"TagResponse">;
export type DomainDto = ApiDto<"Domain">;
export type DomainListResponseDto = ApiDto<"DomainListResponse">;

export type SettingsDto = ApiDto<"Settings">;
export type SettingsPatchDto = ApiDto<"SettingsPatch">;
export type SettingsResponseDto = ApiDto<"SettingsResponse">;
export type ConnectivityTestResponseDto = ApiDto<"ConnectivityTestResponse">;

export type BackupScheduleDto = ApiDto<"BackupSchedule">;
export type BackupSchedulePatchDto = ApiDto<"BackupSchedulePatch">;
export type BackupScheduleResponseDto = ApiDto<"BackupScheduleResponse">;
export type BackupDestinationDto = ApiDto<"BackupDestination">;
export type BackupDestinationPatchDto = ApiDto<"BackupDestinationPatch">;
export type BackupDestinationResponseDto = ApiDto<"BackupDestinationResponse">;
export type BackupResultDto = ApiDto<"BackupResult">;
export type BackupEntryDto = ApiDto<"BackupEntry">;
export type BackupListResponseDto = ApiDto<"BackupListResponse">;
export type BackupVerifyRequestDto = ApiDto<"BackupVerifyRequest">;
export type BackupVerificationResultDto = ApiDto<"BackupVerificationResult">;
export type BackupPackageRequestDto = ApiDto<"BackupPackageRequest">;
export type EncryptedBackupPackageRequestDto = ApiDto<"EncryptedBackupPackageRequest">;
export type EncryptedBackupPackageResultDto = ApiDto<"EncryptedBackupPackageResult">;
export type EncryptedBackupPackageVerificationResultDto = ApiDto<"EncryptedBackupPackageVerificationResult">;
export type RestoreRequestDto = ApiDto<"RestoreRequest">;
export type RestoreResultDto = ApiDto<"RestoreResult">;

export type ImportSummaryDto = ApiDto<"ImportSummary">;
export type ImportSummaryResponseDto = ApiDto<"ImportSummaryResponse">;
export type ImportProgressEventDto = ApiDto<"ImportProgressEvent">;
export type ImportDuplicatePolicyDto = ApiDto<"ImportDuplicatePolicy">;
export type ImportFolderRemappingInputDto = ApiDto<"ImportFolderRemappingInput">;
export type ImportTagRemappingInputDto = ApiDto<"ImportTagRemappingInput">;
export type ImportRemappingInputDto = ApiDto<"ImportRemappingInput">;
export type ImportFolderMappingDto = ApiDto<"ImportFolderMapping">;
export type ImportTagMappingDto = ApiDto<"ImportTagMapping">;
export type ImportRemappingDto = ApiDto<"ImportRemapping">;
export type ImportPreviewSummaryDto = ApiDto<"ImportPreviewSummary">;
export type ImportPreviewRowDto = ApiDto<"ImportPreviewRow">;
export type ImportPreviewDto = ApiDto<"ImportPreview">;
export type ImportPreviewResponseDto = ApiDto<"ImportPreviewResponse">;
export type ImportResultSummaryDto = ApiDto<"ImportResultSummary">;
export type ImportResultRowDto = ApiDto<"ImportResultRow">;
export type ImportResultReportDto = ApiDto<"ImportResultReport">;
export type TimelinePageDto = ApiDto<"TimelinePage">;
export type SuggestionDto = ApiDto<"Suggestion">;
export type SuggestionsResponseDto = ApiDto<"SuggestionsResponse">;
export type HealthResponseDto = ApiDto<"HealthResponse">;
export type DiagnosticsDto = ApiDto<"Diagnostics">;
export type DiagnosticsResponseDto = ApiDto<"DiagnosticsResponse">;
export type UpdateReleaseDto = ApiDto<"UpdateRelease">;
export type UpdateCheckResultDto = ApiDto<"UpdateCheckResult">;
export type UpdateCheckResponseDto = ApiDto<"UpdateCheckResponse">;
export type ExportBookmarkDto = ApiDto<"ExportBookmark">;
