#!/command/with-contenv bash

chown -R grimoire:grimoire /app/data
chmod 755 /app/data

cd /app

# Run migrations first
s6-setuidgid grimoire /usr/local/bin/bun run run-migrations

# Start the application
exec s6-setuidgid grimoire /usr/local/bin/bun ./build/index.js
