import type { CategoryDbo } from './CategoryDbo.type';
import type { TagDbo } from './TagDbo.type';
import type { UserDbo } from './UserDbo.type';
import type { FileDbo } from './FileDbo.type';

export type BookmarkDbo = {
	id: number;
	url: string;
	domain: string;
	title: string;
	description: string | null;
	author: string | null;
	contentText: string | null;
	contentHtml: string | null;
	contentType: string | null;
	contentPublishedDate: string | null;
	note: string | null;
	mainImage?: FileDbo | null;
	mainImageId: number | null;
	mainImageUrl: string | null;
	icon?: FileDbo | null;
	iconId: number | null;
	iconUrl: string | null;
	importance: number | null;
	flagged: null | Date;
	read: null | Date;
	archived: null | Date;
	category: CategoryDbo | null;
	tags: TagDbo[];
	owner: UserDbo;
	openedLast: null | Date;
	openedTimes: number;
	screenshotId: number | null;
	screenshot?: FileDbo | null;
	created: Date;
	updated: Date;
};
