import type {
  BookmarkDetailDto,
  BookmarkDto,
  CategoryNodeDto,
  SettingsDto,
  SuggestionDto,
  TimelinePageDto,
} from "../../../daemon/src/api/types";

export type DemoBookmark = BookmarkDto & {
  content: BookmarkDetailDto["content"];
};

const DEMO_TODAY = "2026-08-21T09:00:00.000Z";

function contentFor(
  id: string,
  title: string,
  description: string | null,
  publishedAt: string | null = null
): NonNullable<BookmarkDetailDto["content"]> {
  const summary = description ?? `A short field guide to ${title.toLowerCase()}.`;
  return {
    bookmark_id: id,
    raw_html: null,
    markdown: `# ${title}\n\n${summary}\n\nThis original demo note highlights the ideas a developer may want to revisit later.`,
    summary,
    author: "Grimoire demo editorial team",
    published_at: publishedAt,
    word_count: 86,
    language: "en",
    extracted_at: DEMO_TODAY,
  };
}

type BookmarkInput = Pick<
  DemoBookmark,
  "id" | "url" | "domain" | "title" | "description" | "category_id" | "tags" | "created_at"
> & Partial<Pick<DemoBookmark, "is_pinned" | "is_archived" | "is_trashed" | "trashed_at" | "read_later" | "read_at" | "opened_count" | "last_opened_at" | "status" | "notes">>;

function bookmark(input: BookmarkInput): DemoBookmark {
  return {
    id: input.id,
    url: input.url,
    domain: input.domain,
    title: input.title,
    description: input.description,
    status: input.status ?? "indexed",
    category_id: input.category_id,
    favicon_url: null,
    screenshot_url: null,
    is_pinned: input.is_pinned ?? 0,
    is_archived: input.is_archived ?? 0,
    is_trashed: input.is_trashed ?? 0,
    trashed_at: input.trashed_at ?? null,
    read_later: input.read_later ?? 0,
    read_at: input.read_at ?? null,
    opened_count: input.opened_count ?? 0,
    last_opened_at: input.last_opened_at ?? null,
    notes: input.notes ?? null,
    created_at: input.created_at,
    updated_at: input.created_at,
    tags: [...input.tags],
    content: contentFor(input.id, input.title ?? input.url, input.description),
  };
}

export const DEMO_BOOKMARKS: readonly DemoBookmark[] = [
  bookmark({
    id: "demo-001",
    url: "https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API",
    domain: "developer.mozilla.org",
    title: "View Transition API",
    description: "A practical reference for animating document and single-page transitions.",
    category_id: "cat-frontend",
    tags: ["web-platform", "frontend", "animation"],
    created_at: "2026-08-21T08:45:00.000Z",
    is_pinned: 1,
    read_at: "2026-08-21T08:50:00.000Z",
    opened_count: 4,
    last_opened_at: "2026-08-21T08:50:00.000Z",
    notes: "Useful when a route change should still feel spatial.",
  }),
  bookmark({
    id: "demo-002",
    url: "https://react.dev/learn/you-might-not-need-an-effect",
    domain: "react.dev",
    title: "You Might Not Need an Effect",
    description: "A clear guide to keeping derived data in render instead of synchronising it with effects.",
    category_id: "cat-frontend",
    tags: ["react", "frontend", "architecture"],
    created_at: "2026-08-20T15:20:00.000Z",
    read_at: "2026-08-20T16:05:00.000Z",
    opened_count: 2,
    last_opened_at: "2026-08-20T16:05:00.000Z",
  }),
  bookmark({
    id: "demo-003",
    url: "https://web.dev/articles/deferring-non-critical-css",
    domain: "web.dev",
    title: "Deferring non-critical CSS",
    description: "Performance patterns for keeping initial rendering focused on what is visible first.",
    category_id: "cat-frontend",
    tags: ["performance", "css", "frontend"],
    created_at: "2026-08-19T12:00:00.000Z",
    read_later: 1,
  }),
  bookmark({
    id: "demo-004",
    url: "https://www.typescriptlang.org/docs/handbook/2/narrowing.html",
    domain: "typescriptlang.org",
    title: "TypeScript: Narrowing",
    description: "The handbook chapter on turning runtime checks into precise static types.",
    category_id: "cat-frontend",
    tags: ["typescript", "types", "tooling"],
    created_at: "2026-08-18T09:30:00.000Z",
    opened_count: 7,
    last_opened_at: "2026-08-19T10:10:00.000Z",
  }),
  bookmark({
    id: "demo-005",
    url: "https://vite.dev/guide/build.html",
    domain: "vite.dev",
    title: "Vite production build guide",
    description: "The reference for building, previewing, and tuning a Vite application.",
    category_id: "cat-tooling",
    tags: ["vite", "tooling", "build"],
    created_at: "2026-08-17T14:15:00.000Z",
    read_later: 1,
  }),
  bookmark({
    id: "demo-006",
    url: "https://nodejs.org/en/learn/getting-started/an-introduction-to-the-npm-package-manager",
    domain: "nodejs.org",
    title: "An introduction to the npm package manager",
    description: "A compact explanation of package manifests, dependencies, and reproducible installs.",
    category_id: "cat-tooling",
    tags: ["node", "npm", "tooling"],
    created_at: "2026-08-16T11:40:00.000Z",
    read_at: "2026-08-17T08:10:00.000Z",
    opened_count: 1,
    last_opened_at: "2026-08-17T08:10:00.000Z",
  }),
  bookmark({
    id: "demo-007",
    url: "https://bun.sh/docs/runtime/sqlite",
    domain: "bun.sh",
    title: "Bun SQLite API",
    description: "Notes on using Bun's built-in SQLite runtime with a small local service.",
    category_id: "cat-backend",
    tags: ["bun", "sqlite", "backend"],
    created_at: "2026-08-15T16:25:00.000Z",
    is_pinned: 1,
    opened_count: 3,
    last_opened_at: "2026-08-16T09:00:00.000Z",
  }),
  bookmark({
    id: "demo-008",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview",
    domain: "developer.mozilla.org",
    title: "An overview of HTTP",
    description: "A durable refresher on requests, responses, methods, headers, and status codes.",
    category_id: "cat-backend",
    tags: ["http", "web-platform", "backend"],
    created_at: "2026-08-14T10:00:00.000Z",
    read_at: "2026-08-15T12:00:00.000Z",
    opened_count: 5,
    last_opened_at: "2026-08-15T12:00:00.000Z",
  }),
  bookmark({
    id: "demo-009",
    url: "https://www.sqlite.org/foreignkeys.html",
    domain: "sqlite.org",
    title: "SQLite foreign key support",
    description: "A reference for enforcing relationships safely in a small embedded database.",
    category_id: "cat-backend",
    tags: ["sqlite", "data", "backend"],
    created_at: "2026-08-13T13:35:00.000Z",
    read_later: 1,
  }),
  bookmark({
    id: "demo-010",
    url: "https://www.postgresql.org/docs/current/transaction-iso.html",
    domain: "postgresql.org",
    title: "Transaction isolation",
    description: "The PostgreSQL reference on visibility, concurrency, and transaction isolation levels.",
    category_id: "cat-backend",
    tags: ["postgres", "transactions", "data"],
    created_at: "2026-08-12T09:50:00.000Z",
    opened_count: 2,
    last_opened_at: "2026-08-12T13:10:00.000Z",
  }),
  bookmark({
    id: "demo-011",
    url: "https://docs.docker.com/build/building/multi-stage/",
    domain: "docs.docker.com",
    title: "Multi-stage builds",
    description: "A guide to keeping production container images small and focused.",
    category_id: "cat-tooling",
    tags: ["docker", "containers", "build"],
    created_at: "2026-08-11T17:05:00.000Z",
    read_at: "2026-08-12T08:00:00.000Z",
  }),
  bookmark({
    id: "demo-012",
    url: "https://docs.github.com/en/actions/writing-workflows/quickstart",
    domain: "docs.github.com",
    title: "GitHub Actions quickstart",
    description: "A starting point for expressing repeatable build and test workflows as code.",
    category_id: "cat-tooling",
    tags: ["github", "ci", "automation"],
    created_at: "2026-08-10T15:45:00.000Z",
    is_archived: 1,
    read_at: "2026-08-10T18:00:00.000Z",
  }),
  bookmark({
    id: "demo-013",
    url: "https://playwright.dev/docs/test-intro",
    domain: "playwright.dev",
    title: "Playwright Test introduction",
    description: "A practical overview of browser test isolation, locators, and traceable failures.",
    category_id: "cat-testing",
    tags: ["playwright", "testing", "e2e"],
    created_at: "2026-08-09T11:15:00.000Z",
    is_pinned: 1,
    read_at: "2026-08-09T12:00:00.000Z",
    opened_count: 9,
    last_opened_at: "2026-08-20T09:30:00.000Z",
  }),
  bookmark({
    id: "demo-014",
    url: "https://vitest.dev/guide/",
    domain: "vitest.dev",
    title: "Vitest guide",
    description: "Fast unit testing patterns for a Vite-native TypeScript codebase.",
    category_id: "cat-testing",
    tags: ["vitest", "testing", "typescript"],
    created_at: "2026-08-08T10:20:00.000Z",
    read_later: 1,
  }),
  bookmark({
    id: "demo-015",
    url: "https://testing-library.com/docs/queries/about/",
    domain: "testing-library.com",
    title: "Testing Library queries",
    description: "A testing philosophy and query guide that keeps assertions close to user behavior.",
    category_id: "cat-testing",
    tags: ["testing", "accessibility", "frontend"],
    created_at: "2026-08-07T09:10:00.000Z",
    read_at: "2026-08-07T10:00:00.000Z",
  }),
  bookmark({
    id: "demo-016",
    url: "https://www.w3.org/WAI/ARIA/apg/",
    domain: "w3.org",
    title: "ARIA Authoring Practices Guide",
    description: "Patterns for making interactive widgets understandable and keyboard operable.",
    category_id: "cat-design-systems",
    tags: ["accessibility", "aria", "design-systems"],
    created_at: "2026-08-06T13:00:00.000Z",
    is_pinned: 1,
    read_at: "2026-08-06T14:00:00.000Z",
    opened_count: 6,
    last_opened_at: "2026-08-19T14:00:00.000Z",
  }),
  bookmark({
    id: "demo-017",
    url: "https://www.nngroup.com/articles/ten-usability-heuristics/",
    domain: "nngroup.com",
    title: "10 usability heuristics for user interface design",
    description: "A durable checklist for evaluating feedback, language, control, and error recovery.",
    category_id: "cat-design-systems",
    tags: ["ux", "heuristics", "design"],
    created_at: "2026-08-05T08:30:00.000Z",
    read_later: 1,
  }),
  bookmark({
    id: "demo-018",
    url: "https://carbondesignsystem.com/guidelines/content/overview/",
    domain: "carbondesignsystem.com",
    title: "Carbon content guidelines",
    description: "A reference for concise product language, hierarchy, and action-oriented interface copy.",
    category_id: "cat-design-systems",
    tags: ["design-systems", "content", "ux"],
    created_at: "2026-08-04T16:40:00.000Z",
    is_archived: 1,
  }),
  bookmark({
    id: "demo-019",
    url: "https://martinfowler.com/articles/patterns-of-distributed-systems/",
    domain: "martinfowler.com",
    title: "Patterns of distributed systems",
    description: "A catalog of small, named solutions for coordination and consistency problems.",
    category_id: "cat-architecture",
    tags: ["architecture", "distributed-systems", "backend"],
    created_at: "2026-08-03T12:20:00.000Z",
    read_at: "2026-08-04T12:00:00.000Z",
    opened_count: 8,
    last_opened_at: "2026-08-18T08:00:00.000Z",
  }),
  bookmark({
    id: "demo-020",
    url: "https://12factor.net/",
    domain: "12factor.net",
    title: "The Twelve-Factor App",
    description: "A concise set of deployment and configuration principles for service applications.",
    category_id: "cat-architecture",
    tags: ["architecture", "operations", "deployment"],
    created_at: "2026-08-02T09:45:00.000Z",
    read_later: 1,
  }),
  bookmark({
    id: "demo-021",
    url: "https://owasp.org/www-project-application-security-verification-standard/",
    domain: "owasp.org",
    title: "OWASP Application Security Verification Standard",
    description: "A structured security baseline for reviewing authentication, validation, and data handling.",
    category_id: "cat-security",
    tags: ["security", "web", "review"],
    created_at: "2026-08-01T14:25:00.000Z",
    is_pinned: 1,
    read_at: "2026-08-02T10:00:00.000Z",
    opened_count: 3,
    last_opened_at: "2026-08-17T15:30:00.000Z",
  }),
  bookmark({
    id: "demo-022",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP",
    domain: "developer.mozilla.org",
    title: "Content Security Policy",
    description: "A reference for constraining browser resource loading and reducing injection impact.",
    category_id: "cat-security",
    tags: ["security", "csp", "web-platform"],
    created_at: "2026-07-31T11:10:00.000Z",
    read_at: "2026-08-01T09:30:00.000Z",
  }),
  bookmark({
    id: "demo-023",
    url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html",
    domain: "cheatsheetseries.owasp.org",
    title: "Authentication cheat sheet",
    description: "Implementation reminders for passwords, sessions, recovery, and multi-factor authentication.",
    category_id: "cat-security",
    tags: ["security", "authentication", "review"],
    created_at: "2026-07-30T08:35:00.000Z",
    read_later: 1,
  }),
  bookmark({
    id: "demo-024",
    url: "https://research.google/pubs/large-scale-deep-learning-for-intelligent-computer-assisted-language-learning/",
    domain: "research.google",
    title: "Large-scale deep learning research",
    description: "A research paper landing page included to make the demo library useful beyond documentation.",
    category_id: "cat-research",
    tags: ["research", "machine-learning", "reading"],
    created_at: "2026-07-29T17:00:00.000Z",
    is_archived: 1,
  }),
  bookmark({
    id: "demo-025",
    url: "https://arxiv.org/abs/1706.03762",
    domain: "arxiv.org",
    title: "Attention Is All You Need",
    description: "The paper page for the transformer architecture, saved as a research reference.",
    category_id: "cat-research",
    tags: ["research", "machine-learning", "foundations"],
    created_at: "2026-07-28T13:30:00.000Z",
    opened_count: 11,
    last_opened_at: "2026-08-20T11:00:00.000Z",
  }),
  bookmark({
    id: "demo-026",
    url: "https://docs.python.org/3/library/asyncio.html",
    domain: "docs.python.org",
    title: "asyncio — Asynchronous I/O",
    description: "The Python standard-library reference for cooperative concurrency and event loops.",
    category_id: "cat-backend",
    tags: ["python", "async", "backend"],
    created_at: "2026-07-27T10:15:00.000Z",
    read_at: "2026-07-27T11:00:00.000Z",
  }),
  bookmark({
    id: "demo-027",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    domain: "developer.mozilla.org",
    title: "JavaScript Promise reference",
    description: "A reference for composing asynchronous work and handling fulfillment or rejection.",
    category_id: "cat-frontend",
    tags: ["javascript", "async", "frontend"],
    created_at: "2026-07-26T07:55:00.000Z",
    is_trashed: 1,
    trashed_at: "2026-08-18T18:00:00.000Z",
  }),
  bookmark({
    id: "demo-028",
    url: "https://git-scm.com/book/en/v2",
    domain: "git-scm.com",
    title: "Pro Git book",
    description: "A deep but approachable reference for everyday Git workflows and repository internals.",
    category_id: "cat-tooling",
    tags: ["git", "tooling", "workflow"],
    created_at: "2026-07-25T15:20:00.000Z",
    read_later: 1,
  }),
  bookmark({
    id: "demo-029",
    url: "https://semver.org/",
    domain: "semver.org",
    title: "Semantic Versioning 2.0.0",
    description: "The specification for communicating compatibility through version numbers.",
    category_id: "cat-architecture",
    tags: ["release", "versioning", "tooling"],
    created_at: "2026-07-24T11:00:00.000Z",
    read_at: "2026-07-24T11:30:00.000Z",
  }),
  bookmark({
    id: "demo-030",
    url: "https://www.w3.org/TR/wcag-quickref/",
    domain: "w3.org",
    title: "How to meet WCAG quick reference",
    description: null,
    category_id: "cat-design-systems",
    tags: ["accessibility", "standards", "design"],
    created_at: "2026-07-23T09:00:00.000Z",
    is_pinned: 1,
  }),
];

function category(
  id: string,
  name: string,
  parentId: string | null,
  children: CategoryNodeDto[] = []
): CategoryNodeDto {
  return {
    id,
    name,
    parent_id: parentId,
    color: null,
    icon: null,
    description: null,
    slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    is_archived: 0,
    is_public: 0,
    created_at: "2026-07-01T09:00:00.000Z",
    updated_at: "2026-08-21T09:00:00.000Z",
    bookmark_count: 0,
    children,
  };
}

export const DEMO_CATEGORIES: readonly CategoryNodeDto[] = [
  category("cat-engineering", "Engineering", null, [
    category("cat-frontend", "Frontend", "cat-engineering"),
    category("cat-backend", "Backend", "cat-engineering"),
    category("cat-testing", "Testing", "cat-engineering"),
    category("cat-tooling", "Tooling", "cat-engineering"),
    category("cat-architecture", "Architecture", "cat-engineering"),
    category("cat-security", "Security", "cat-engineering"),
  ]),
  category("cat-design", "Design", null, [
    category("cat-design-systems", "Design systems", "cat-design"),
  ]),
  category("cat-research", "Research", null),
];

export const DEMO_SETTINGS: SettingsDto = {
  ai: {
    provider: "none",
    openai: { api_key: "", model: "gpt-4o-mini" },
    ollama: { base_url: "https://example.invalid/ollama", model: "llama3" },
    anthropic: { api_key: "", base_url: "https://example.invalid/anthropic", model: "claude-sonnet" },
    openrouter: { api_key: "", base_url: "https://example.invalid/openrouter", model: "openai/gpt-latest" },
    openai_compatible: { api_key: "", base_url: "https://example.invalid/ai", model: "custom-chat-model" },
    deepseek: { api_key: "", base_url: "https://example.invalid/deepseek", model: "deepseek-chat" },
    embeddings: {
      provider: "openai",
      model: "text-embedding-3-small",
      openai_compatible: { api_key: "", base_url: "https://example.invalid/embeddings", model: "custom-embedding-model" },
    },
  },
  app: { autostart: false, theme: "system", lock: { enabled: false, pin_hash: "" } },
  backup: {
    local: { destination_path: "" },
    schedule: { enabled: false, cron: "0 3 * * *", retention_count: 7 },
    s3: { endpoint: "", bucket: "", access_key: "", secret_key: "", region: "us-east-1", prefix: "grimoire-demo/" },
  },
  runtime: {
    llm: { enabled: false, provider: "none", model: null, base_url: null },
    embeddings: { enabled: false, provider: "openai", model: "text-embedding-3-small", base_url: "https://example.invalid/embeddings" },
    capabilities: { enrichment: false, semantic_search: false, related_bookmarks: false, organization_agent: false },
  },
};

export const DEMO_TIMELINE: ReadonlyArray<TimelinePageDto["data"][number]> = [
  {
    id: "timeline-001",
    type: "category_created",
    description: "Created the Engineering category",
    metadata: { category_id: "cat-engineering" },
    source: "user",
    created_at: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "timeline-002",
    type: "cluster_labeled",
    description: "Grouped frontend references under Frontend",
    metadata: { category_id: "cat-frontend", count: 5 },
    source: "agent",
    created_at: "2026-08-18T14:30:00.000Z",
  },
  {
    id: "timeline-003",
    type: "duplicate_flagged",
    description: "Flagged two similar HTTP references for review",
    metadata: { bookmark_ids: ["demo-008", "demo-022"] },
    source: "agent",
    created_at: "2026-08-16T09:15:00.000Z",
  },
  {
    id: "timeline-004",
    type: "category_renamed",
    description: "Renamed the design category to Design systems",
    metadata: { category_id: "cat-design-systems" },
    source: "user",
    created_at: "2026-08-12T16:00:00.000Z",
  },
  {
    id: "timeline-005",
    type: "category_merge_suggested",
    description: "Suggested reviewing overlapping accessibility categories",
    metadata: { category_ids: ["cat-design-systems", "cat-security"] },
    source: "agent",
    created_at: "2026-08-09T11:30:00.000Z",
  },
  {
    id: "timeline-006",
    type: "suggestion_rejected",
    description: "Rejected a category merge suggestion",
    metadata: { suggestion_id: "suggestion-002" },
    source: "user",
    created_at: "2026-08-05T13:00:00.000Z",
  },
];

export const DEMO_SUGGESTIONS: readonly SuggestionDto[] = [
  {
    id: "suggestion-001",
    bookmarkId: "demo-016",
    type: "new_subcategory",
    value: "Create an Accessibility subcategory under Design",
    metadata: { category_id: "cat-design" },
    confidence: 0.88,
    status: "pending",
    created_at: "2026-08-19T10:00:00.000Z",
    resolved_at: null,
  },
  {
    id: "suggestion-002",
    bookmarkId: "demo-008",
    type: "duplicate_bookmark",
    value: "Review the overlapping HTTP and CSP references",
    metadata: { bookmark_ids: ["demo-008", "demo-022"] },
    confidence: 0.72,
    status: "pending",
    created_at: "2026-08-17T15:00:00.000Z",
    resolved_at: null,
  },
];
